language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

build:
    ci:
        - mkdir -p shippable/codecoverage
        - pip install -e .
        - coverage run ./setup.py test
        - coverage xml --include 'tv_report*' -o shippable/codecoverage/coverage.xml
        - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
